### ISSUE TITLE
[TPHY] Webhis与医保接口门诊挂号数据传输问题

### ISSUE THREAD

**Issue by smallprogram** [smallprogram/Tphy_Cgyy_Issues#18]
## 问题描述
目前HIS与医保系统通过医保专用网络传输，由于网络有波动情况，有时会导致医保系统数据没有传输过去，有时又会导致HIS系统数据回写丢失。间接导致HIS系统与医保系统在挂号上差账。

## 需求
需要HIS系统在医保挂号模块上加入网络监测与数据监测手段，防止以上问题的发生。

## 近期出现的问题
7月29日，HIS系统，病人ID 0000098770 挂号费10元，与病人ID 0000421416 挂号费用25，在医保系统中丢失该挂号信息。这就导致该笔费用医保不予报销。
7月30日，HIS系统，病人ID 0000401517 挂号费10元，在医保系统中丢失该挂号信息。这就导致该笔费用医保不予报销。
7月31日，HIS系统，病人ID 0000323339挂号费10元，在医保系统中丢失该挂号信息。
8月  1日，HIS系统，病人ID 0000041171挂号费10元，在医保系统中丢失该挂号信息。
8月  2日，HIS系统，病人ID 0000356879挂号费10元，在医保系统中丢失该挂号信息．
8月  2日，HIS系统，病人ID 0000263726挂号费15元，在医保系统中丢失该挂号信息．
8月  4日，HIS系统，病人ID 0000416881挂号费10元，在医保系统中丢失该挂号信息．
8月  5日，HIS系统，病人ID 0000043751挂号费10元，在医保系统中丢失该挂号信息．
8月  5日，HIS系统，病人ID 0000401286挂号费10元，在医保系统中丢失该挂号信息．
## 网络监测
![image](https://user-images.githubusercontent.com/6050360/62338606-ae985f80-b50b-11e9-874b-c82670f6e920.png)
**医保网络监测未发现网络延迟,ping延迟情况,没有丢包和高延迟状态**
## 系统错误提示
**系统偶尔会提示该错误**
![image](https://user-images.githubusercontent.com/6050360/62338650-d982b380-b50b-11e9-8c9a-b72c6c45f066.png)

**Comment by smallprogram** [comment]
7月30日，HIS系统，病人ID 0000401517 挂号费10元，在医保系统中丢失该挂号信息。这就导致该笔费用医保不予报销。

**Comment by smallprogram** [comment]
7月31日，HIS系统，病人ID 0000323339挂号费10元，在医保系统中丢失该挂号信息。

**Comment by smallprogram** [comment]
监测网络延迟,ping延迟情况,没有丢包和高延迟状态

**Comment by smallprogram** [comment]
8月1日，HIS系统，病人ID 0000041171 挂号费10元，在医保系统中丢失该挂号信息。

**Comment by smallprogram** [comment]
TPHY检测发现，HIS挂号完毕回写医保数据时没有添加验证逻辑。导致数据回写失败时没有提示。

**Comment by smallprogram** [comment]
程华，准备换包

**Comment by smallprogram** [comment]
已换包，准备验收

**Comment by smallprogram** [comment]
验收不通过，
## 新BUG
医保挂号失败后HIS会多出充值记录

**Comment by smallprogram** [comment]
程华准备换包

**Comment by smallprogram** [comment]
程华已换包，准备验收

**Comment by smallprogram** [comment]
换包之后引发新ＢＵＧ
## 新BUG
### 问题1
医保系统收费完毕之后，Webhis **收费单据录入**模块更新报销信息之后，会提示录入金额必须大于等于应补金额。并且丢失充值记录
![image](https://user-images.githubusercontent.com/6050360/62747543-836fbc00-ba87-11e9-81cb-33c36936b331.png)
### 问题2
部分患者，医生开据项目之后，在**收费单据录入**模块中，无法获取到医生开据的医嘱，进而无法收费。例如患者就诊卡9049365

**Comment by smallprogram** [comment]
再次换包，出现大批患者充值记录丢失情况

**Comment by baixueping123** [comment]
王丰已修改程序
