### ISSUE TITLE
[TPHY] Webhis患者退号丢失取现记录

### ISSUE THREAD

**Issue by smallprogram** [smallprogram/Tphy_Cgyy_Issues#21]
## 患者信息
患者编号: 0000365423  
姓名: 张桂珍
## 问题描述
8月3日，该患者退号之后。有退号记录,没有取现记录 . 
### 退号记录截图
![image](https://user-images.githubusercontent.com/6050360/62432329-ae919d00-b761-11e9-83c6-b521eb2b546d.png)
### 取现记录丢失截图
![image](https://user-images.githubusercontent.com/6050360/62432348-c49f5d80-b761-11e9-81a8-67cebe90b0c2.png)

**Comment by baixueping123** [comment]
王丰已调整
