### ISSUE TITLE
[TPHY](2019年8月6日) EMR打印处方新增需求

### ISSUE THREAD

**Issue by smallprogram** [smallprogram/Tphy_Cgyy_Issues#23]
## 原始需求链接
[原始需求](https://github.com/smallprogram/Tphy_Cgyy_Issues/issues/5)
#### 图一
![image](https://user-images.githubusercontent.com/6050360/62506201-4068db00-b832-11e9-828b-e8521f1caeb3.png)
#### 图二
![image](https://user-images.githubusercontent.com/6050360/63145287-6c057580-c029-11e9-8b1d-5bae57a986ca.png)

- 要求打印A4纸的一半
- 格式元素严格按照图二进行设置
- 图二未标记生成的地方空着就行，让用户手填
### EMR打印方式
- 取消只生成毒麻药品的限制。只要是药品就可以生成处方。
- 无论**长期医嘱还是临时医嘱，取消之前的默认规则**，全部**改为手动选择医嘱打印医嘱处方**。让**操作者自己选择需要打印的医嘱**。
- 生成的打印处方，只打印操作者选择的医嘱。
- 需要注意，**如果操作者选择了非药品，生成的处方应该为空，或者给提示选择的医嘱不不是药品医嘱，不能生成处方**。
- EMR右键菜单中的“毒麻精处方打印”，**改为“处方打印”**

**Comment by smallprogram** [comment]
添加问题解释
![image](https://user-images.githubusercontent.com/6050360/63853828-3b7cee80-c9ce-11e9-8c0d-b4f0ea4cf35a.png)
![image](https://user-images.githubusercontent.com/6050360/63853841-420b6600-c9ce-11e9-8de0-a350664c1273.png)

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/64144723-75277c80-ce48-11e9-8e66-60d437cc2354.png)
新包效果演示，等待测试验证

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/64153192-e6732980-ce60-11e9-870d-c91d8aeabdf8.png)
![image](https://user-images.githubusercontent.com/6050360/64153195-e96e1a00-ce60-11e9-8bbf-a5e38de1a74d.png)
### 由于可是名称长度问题，导致后方文字丢失，需要修正

**Comment by smallprogram** [comment]
### 最新需求
![image](https://user-images.githubusercontent.com/6050360/64228278-e5053800-cf18-11e9-87bc-10f100c5b938.png)
- 需要增加门诊号： 处方编号：
- 处方内容需要按照黄色方框内的格式显示，注意需要换行
- 处方内容的说明已经再图片中标注，可以参考，注意其中【药品单位规格*需用数量】即日用量的计算方式
- 其他未标注的地方一律空着，让用户手动填写，标注为手填的也让用户手动填写

**Comment by TPHY-QiYaFeng** [comment]
已换包

**Comment by smallprogram** [comment]
> 已换包

等待科室确认

**Comment by smallprogram** [comment]
> 已换包

![image](https://user-images.githubusercontent.com/6050360/67348276-f06afc00-f576-11e9-8cab-0e2be9dc829d.png)
与需求不符，需要重新反馈

**Comment by smallprogram** [comment]
> > 已换包

![image](https://user-images.githubusercontent.com/6050360/67375232-e962de80-f5b4-11e9-91d0-3f930fd1dd8c.png)

**Comment by smallprogram** [comment]
等待周一与药剂科主任沟通

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/67916030-6b639080-fbcf-11e9-8446-5a9c7a5368d4.png)
与药剂科主任沟通，确认符合需求，问题关闭

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/68260394-e4ebfa80-0077-11ea-9f5a-0454c8b9af4e.png)

修复开具日期 年 月  日  丢字的情况

**Comment by smallprogram** [comment]
格式年月日修复。暂时关闭该问题
