### ISSUE TITLE
[TPHY] Webhis住院汇总与财务实际收入不符

### ISSUE THREAD

**Issue by smallprogram** [smallprogram/Tphy_Cgyy_Issues#30]
## 问题描述
财务科，8月22日，住院实际收入如下：

|POS机收入|现金收入|医保收入|合计|
| --- | --- | --- | --- |
|17817.74|39596.31|86098.69|143512.7|

WebHis系统，8月22日，住院汇总结账单：
![image](https://user-images.githubusercontent.com/6050360/63631040-8ad0c100-c654-11e9-9df4-eb30d19bda9b.png)

![image](https://user-images.githubusercontent.com/6050360/63631044-93c19280-c654-11e9-9b70-b666f02db26f.png)

## 正常情况：
**HIS 交付预交金-收回出院患者押金+结算费用收入 = 财务科住院实际收入**

## 目前情况：

交付预交金|收回出院患者押金|结算费用收入|HIS合计|财务实际收入合计|差额
-|-|-|-|-|-
42400+4000|30400|151944|167994|143512.7|24481.3

## 有可能导致差账的原因：

由于之前[#29](https://github.com/smallprogram/Tphy_Cgyy_Issues/issues/29) 问题，重复提交导致差账。多算了一次该患者的数据。

**Comment by FengTPHY** [comment]
![image](https://user-images.githubusercontent.com/54595364/63793037-62391780-c931-11e9-867b-cfc64cee21c0.png)

**Comment by FengTPHY** [comment]
![image](https://user-images.githubusercontent.com/54595364/63793462-5437c680-c932-11e9-8960-d8ab43184aa9.png)

**Comment by FengTPHY** [comment]
交付预交金 | 收回出院患者押金 | 结算费用收入 | HIS合计 | 财务实际收入合计 | 差额
-- | -- | -- | -- | -- | --
42400+4000| 30400 | 127512.74 | 143512.74 | 143512.74 | 0

**Comment by smallprogram** [comment]
财务科正在核对，暂时关闭该问题
