### ISSUE TITLE
[TPHY](2019年8月28日) CPOE床位费自动计费重复收取

### ISSUE THREAD

**Issue by smallprogram** [smallprogram/Tphy_Cgyy_Issues#31]
## 问题描述
神经外科 患者 141888 
CPOE床位费重复收取
护士操作员号：0088 0000
![image](https://user-images.githubusercontent.com/6050360/63818207-849f5500-c972-11e9-9692-0baf787d4e84.png)

**Comment by FengTPHY** [comment]
![image](https://user-images.githubusercontent.com/54595364/63862610-6de31780-c9df-11e9-91d4-a127935972a4.png)
这个是该患者床位记录 最后再sw03床位

**Comment by FengTPHY** [comment]
![image](https://user-images.githubusercontent.com/54595364/63862838-d29e7200-c9df-11e9-8ab9-e294dd551092.png)
床位信息维护有误
正常患者自动计费 一次床位费一次住院诊查费
在这个床位上住院的患者 每天收取两条床位费
数据我没有修改 等明天医院上班 院方修改一下即可
注意:如果该床位上已有相关患者,需要修改完字典表后,再退床重新分床自动计费才能正常

**Comment by smallprogram** [comment]
> ![image](https://user-images.githubusercontent.com/54595364/63862838-d29e7200-c9df-11e9-8ab9-e294dd551092.png)
> 床位信息维护有误
> 正常患者自动计费 一次床位费一次住院诊查费
> 在这个床位上住院的患者 每天收取两条床位费
> 数据我没有修改 等明天医院上班 院方修改一下即可
> 注意:如果该床位上已有相关患者,需要修改完字典表后,再退床重新分床自动计费才能正常

好的，我会处理这个问题

**Comment by smallprogram** [comment]
与神外护士沟通，已自行解决该问题
