### ISSUE TITLE
[TPHY](2019年8月28日) Webhis医技核对显示数量错误

### ISSUE THREAD

**Issue by smallprogram** [smallprogram/Tphy_Cgyy_Issues#32]
## 问题描述
医技管理-医技核对里，数量显示不对。
医生开据医技项目数量为4，在医技核对模块中，显示数量为1.
## 相关截图
![image](https://user-images.githubusercontent.com/6050360/63821067-32643100-c97e-11e9-8ec4-755353ce3559.png)
![image](https://user-images.githubusercontent.com/6050360/63821073-385a1200-c97e-11e9-94e5-fa03e0e21943.png)

**Comment by FengTPHY** [comment]
![image](https://user-images.githubusercontent.com/54595364/63864778-ff07bd80-c9e2-11e9-97cd-d7c293d78e97.png)
已指派给公司相关研发处理

**Comment by smallprogram** [comment]
陈华已换包，准本验收

**Comment by smallprogram** [comment]
暂时关闭该问题
