### ISSUE TITLE
[TPHY](2019年6月5日) WebHis门诊开据和执行科室相同费用不能自动核对

### ISSUE THREAD

**Issue by smallprogram** [smallprogram/Tphy_Cgyy_Issues#7]
门诊开据科室和执行科室相同时，项目费用不能自动核对，需要改为自动核对
(需求)[6月5日]

**Comment by TPHY-QiYaFeng** [comment]
查看参数后，没有问题了

**Comment by smallprogram** [comment]
> 查看参数后，没有问题了

暂时关闭该问题

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/68444036-a5a4e180-0210-11ea-8440-38b39a888e03.png)
![image](https://user-images.githubusercontent.com/6050360/68444050-accbef80-0210-11ea-9487-b0d4ade1d53d.png)

患者就诊卡 9066011

开具科室与执行科室相同不自动核对

**Comment by smallprogram** [comment]
2019年11月20日09点02分 工程师反馈，已经修正系统参数，需要继续观察，暂时关闭该问题
